version: "3"

services:
  bench:
    image: frappe/bench:latest
    privileged: true
    restart: "no"
    working_dir: /home/frappe
    ports:
      - 1080:8000
    volumes:
      - bench_vol:/home/frappe
    command: >
        bash -c "set -e
        && bench init --skip-redis-config-generation --frappe-path ${FRAPPE_REPO} --frappe-branch ${FRAPPE_BRANCH} bench
        && cd bench
        && bench set-mariadb-host mariadb
        && bench set-redis-cache-host redis_cache:6379
        && bench set-redis-queue-host redis_queue:6379
        && bench set-redis-socketio-host redis_socketio:6379
        && bench new-site erp.localhost --mariadb-root-password ${INIT_PASSWORD} --admin-password ${INIT_PASSWORD} --no-mariadb-socket || true
        && bench get-app --branch ${ERPNEXT_BRANCH} erpnext ${ERPNEXT_REPO} || true
        && bench --site erp.localhost install-app erpnext || true
        && bench start --no-dev --no-prefix"

  redis_socketio:
    image: redis:latest
    restart: on-failure
    volumes:
      - redis_socketio_vol:/data

  redis_cache:
    image: redis:latest
    restart: on-failure
    volumes:
      - redis_cache_vol:/data

  redis_queue:
    image: redis:latest
    restart: on-failure
    volumes:
      - redis_queue_vol:/data

  mariadb:
    image: mariadb:10.3
    restart: on-failure
    environment:
      - MYSQL_ROOT_PASSWORD=${INIT_PASSWORD}
    volumes:
      - ./mariadb.cnf:/etc/mysql/conf.d/frappe.cnf
      - mariadb_vol:/var/lib/mysql

volumes:
  mariadb_vol:
  redis_cache_vol:
  redis_queue_vol:
  redis_socketio_vol:
  bench_vol:
